### ISSUE TITLE
rename? feel free to ignore

### ISSUE THREAD

**Issue by quarterto** [SRugina/tache#2]
hi. i've been working on https://github.com/quarterto/tache for the past few weeks. it's a task runner, and `tâche` is French for `task`. it's one of the only names that i've been able to find on npm that's concise and means something.

you can ignore this if you want, and i'll find a new name. i was almost ready to release this week, and was really surprised when the name was suddenly unavailable. i would be really really grateful if i could use that name, but if not, i wish you and your project all the best (it looks really slick btw).

peace and love,

bren

**Comment by SRugina** [comment]
Dear Bren,

Thanks for reaching out to me about this issue. I'd be happy

**Comment by quarterto** [comment]
thank you so much!

**Comment by quarterto** [comment]
great, thank you so much

**Comment by SRugina** [comment]
I've unpublished the tache package. Its name will be blocked from reuse for 24 hours, but then you'll be able to publish to it.
